# Generated by Django 4.0.4 on 2022-05-26 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_comment_phonerequest_remove_application_type_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Application',
            new_name='Question',
        ),
    ]
