# Generated by Django 4.0.4 on 2022-05-26 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_application_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=15)),
                ('email', models.EmailField(blank=True, max_length=50)),
                ('group_area', models.CharField(choices=[('music', 'музыкальное'), ('sport', 'спортивное'), ('art', 'творческое')], max_length=15)),
                ('group_age', models.CharField(choices=[('small', 'младшая'), ('large', 'старшая'), ('medium', 'средняя')], max_length=15)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='question',
            name='message',
        ),
        migrations.AddField(
            model_name='question',
            name='question',
            field=models.TextField(default='', max_length=300),
        ),
    ]
