# Generated by Django 4.0.4 on 2022-07-12 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_application_group_age_alter_pictures_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='group_age',
            field=models.CharField(choices=[('medium', 'средняя'), ('small', 'младшая'), ('large', 'старшая')], max_length=15, verbose_name='Возраст'),
        ),
        migrations.AlterField(
            model_name='application',
            name='group_area',
            field=models.CharField(choices=[('sport', 'спортивное'), ('art', 'творческое'), ('music', 'музыкальное')], max_length=15, verbose_name='Направление'),
        ),
    ]
