# Generated by Django 4.0.4 on 2022-07-12 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_application_group_age_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pictures',
            new_name='Picture',
        ),
        migrations.AlterField(
            model_name='application',
            name='group_age',
            field=models.CharField(choices=[('large', 'старшая'), ('medium', 'средняя'), ('small', 'младшая')], max_length=15, verbose_name='Возраст'),
        ),
        migrations.AlterField(
            model_name='application',
            name='group_area',
            field=models.CharField(choices=[('music', 'музыкальное'), ('sport', 'спортивное'), ('art', 'творческое')], max_length=15, verbose_name='Направление'),
        ),
    ]
