# Generated by Django 4.0.4 on 2022-10-25 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_application_group_area_alter_picture_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='group_area',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='email',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='question',
            name='question',
        ),
        migrations.AlterField(
            model_name='application',
            name='phone_number',
            field=models.CharField(max_length=20, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='phonerequest',
            name='phone_number',
            field=models.CharField(max_length=20, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='picture',
            name='text',
            field=models.TextField(blank=True, default='', max_length=300, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='picture',
            name='title',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='question',
            name='phone_number',
            field=models.CharField(max_length=20, verbose_name='Номер телефона'),
        ),
    ]
