# Generated by Django 4.0.4 on 2022-10-25 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_application_group_age_alter_comment_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.TextField(max_length=300, verbose_name='Комментарий'),
        ),
    ]
